export { default as PatrolConfig } from './PatrolConfig.vue'
export { default as PatrolReport } from './PatrolReport.vue'
export { default as TaskManager } from './TaskManager.vue'
export { default as TaskPatch } from './TaskPatch.vue'
export { default as TaskView } from './TaskView.vue'
